#!/bin/sh

# PROVIDE: duplicacyupd
# REQUIRE: LOGIN FILESYSTEMS netwait
# KEYWORD: SHUTDOWN

. /etc/rc.subr

name=duplicacyupd
rcvar=${name}_enable

load_rc_config $name

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -H -o \"/var/log/${name}.log\" \
    -P \"${pidfile}\" -u root /usr/local/bin/duplicacy-updater "


run_rc_command "$1"
